# Starter pipeline
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: azure-aks-django
  containerRegistry: taoregistry
  tag: $(Build.BuildId)

steps:
  - script: |
      echo 'Print All Parameters:'
      echo 'Build ID: ' $(tag)
      echo 'Build number' $(Build.BuildNumber)
  - script: make test
  - script: make build VERSION=$(Build.BuildId)

  - task: Docker@1
    displayName: push
    inputs:
      azureSubscriptionEndpoint: 'ARM-CCC-Sandbox-SIA'
      azureContainerRegistry: taoregistry
      command: push
      imageName: '$(imageName):$(Build.BuildId)'
      includeSourceTags: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "manifests"
      ArtifactName: "manifests"
      publishLocation: "Container"
