# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    jobs:
      - job: build
        steps:
          - script: |
              echo Add other tasks to build, test, and deploy your project.
              echo See https://aka.ms/yaml
            displayName: "Run a multi-line script"
          - script: make build
      - job: test
        steps:
          - script: make test
      - job: push
        steps:
          - script: make push

  - stage: deploy
    jobs:
      - job: deploy
        steps:
          - task: HelmDeploy@0
            inputs:
              connectionType: "Azure Resource Manager"
              azureResourceGroup: "tao-test"
              kubernetesCluster: "tao-test"
              namespace: "test"
              command: "ls"
