# Starter pipeline
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: azure-aks-django
  azureContainerRegistry: devsoacr
  imageTag: $(Build.BuildId)

steps:
  - script: |
      echo 'Print All Parameters:'
      echo 'Build ID: ' $(imageTag)
      echo 'Build number' $(Build.BuildNumber)
  # - script: make test
  # - script: make build VERSION=$(imageTag)

  - task: Docker@2
    displayName: "Build and push"
    inputs:
      containerRegistry: "taoregistry"
      repository: "tao-aks-django"
      command: "buildAndPush"
      tags: |
        $(imageTag)

  # - script: make push VERSION=$(imageTag)
  # - script: docker logout $(azureContainerRegistry)

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "manifests"
      ArtifactName: "manifests"
      publishLocation: "Container"
