# Starter pipeline
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: azure-aks-django
  containerRegistry: taoregistry
  tag: $(Build.BuildId)

steps:
  - script: |
      echo 'Print All Parameters:'
      echo 'Build ID: ' $(tag)
      echo 'Build number' $(Build.BuildNumber)
  - script: make test

  - task: Docker@2
    displayName: Push image
    inputs:
      containerRegistry: $(containerRegistry)
      repository: $(imageName)
      command: push
      tags: |
        latest
        $(Build.BuildID)

  - script: make push VERSION=$(Build.BuildId)

  # - script: touch foo
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "manifests"
      ArtifactName: "manifests"
      publishLocation: "Container"
